spring:
  profiles:
    active: ${ZALANCE_COVID_ENV:local}
  application:
    name: zalance-covid-19-svc

  datasource:
    url: jdbc:postgresql://192.168.0.99:5432/covid_19
    username: jet
    password: cnh2n+2FN
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: 192.168.0.99
    port: 5672
    username: JeanElisee
    password: cnh2n+2FN



#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: group_id
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.zalance.covid.*
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org:
    springframework:
      web: DEBUG
      security: DEBUG

server:
  port: ${ZALANCE_COVID_PORT:7071}
jwt:
  secret: covid19keyjwt-GHIOU7867gj
api-call:
  url:
    country: https://api.covid19api.com/countries
    daily-summary: https://api.covid19api.com/summary
zalance:
  scheduler:
    enabled: false
  admin:
    name: Jean-Elisée
    phone-number: +919606770337
    email: jeanelisee@gmail.com
  notification:
    max-retry:
      value: 2
    retry:
      enable: true
      x-msg-ttl: 60
  sms:
    enable: true
    company-name: Zalance
    api-key: df1d1b7c
    api-secret: j8yv8MWp6k6d92Fs
  push-notification:
    enable: true
    configuration-file: appui-permis-firebase-adminsdk-3zjr5-24fa1271e7.json
  email:
    enable: true
    company:
      address: info@zalance.com
      name: Zalance
    api-key: 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
  retry:
    queue:
      covid:
        name:
          country: zalance.covid.country.retry.queue.cloud
          cases: zalance.covid.cases.retry.queue.cloud
    exchange:
      name: zalance.covid.deadletter.exchange
  queue:
    covid:
      name:
        country: zalance.covid.country.queue.cloud
        cases: zalance.covid.cases.queue.cloud
    name:
      email: zalance.email.queue.cloud
      push-notification: zalance.push-notification.queue.cloud
      sms: zalance.sms.queue.cloud
  exchange:
    name: zalance.notification.exchange

  message:
    template:
      path:
        push:
          welcome: /templates/messages/push/welcome-push.vm
        sms:
          welcome: /templates/messages/sms/welcome-sms.vm
          report: /templates/messages/sms/report.vm
        mail:
          report: